CREATE DATABASE IF NOT EXISTS ideasdb;

CREATE TABLE IF NOT EXISTS ideasdb.EightMinuteRequests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  gender VARCHAR(50),
  mobile VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

